name: Discord Webhook

on: [push]

jobs:
  git:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Run Discord Webhook
      uses: johnnyhuy/discord-webhook@main
      with:
        webhook_url: ${{ secrets.https://discord.com/api/webhooks/893407054717419543/907cH3T_lhupUTulBicYBLd5WzmJcqf8mMWOaueaV4aG1aP0XYRsHDE-E0AR6Fhgxf45 }}

    # Disable URL links to the repository
    # 
    # - name: Run Discord Webhook
    #   uses: johnnyhuy/discord-webhook@main
    #   with:
    #     webhook_url: ${{ secrets.YOUR_DISCORD_WEBHOOK_URL }}
    #     hide_links: true

    # Censor username
    # 
    # - name: Run Discord Webhook
    #   uses: johnnyhuy/discord-webhook@main
    #   with:
    #     webhook_url: ${{ secrets.YOUR_DISCORD_WEBHOOK_URL }}
    #     censor_username: false

    # Using an ID and token
    # 
    # - name: Run Discord Webhook
    #   uses: johnnyhuy/discord-webhook@main
    #   with:
    #     id: ${{ secrets.YOUR_DISCORD_WEBHOOK_ID }}
    #     token: ${{ secrets.YOUR_DISCORD_WEBHOOK_TOKEN }}

    # Using a custom repo name
    # 
    # - name: Run Discord Webhook
    #   uses: johnnyhuy/discord-webhook@main
    #   with:
    #     id: ${{ secrets.YOUR_DISCORD_WEBHOOK_ID }}
    #     token: ${{ secrets.YOUR_DISCORD_WEBHOOK_TOKEN }}
    #     repo_name: My Special Repo
