name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Clone cosmos
      run: git clone --single-branch --branch crossplatform https://github.com/CosmosOS/Cosmos
    - name: Clone IL2CPU
      run: git clone --single-branch --branch crossplatform https://github.com/CosmosOS/IL2CPU
    - name: Clone X#
      run: git clone https://github.com/CosmosOS/XSharp
    - name: Clone Common
      run: git clone https://github.com/CosmosOS/Common
    - name: Build cosmos
      run: sudo make -C Cosmos
    - name: Install cosmos
      run: sudo make install -C Cosmos
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
